### ISSUE TITLE
Dependency Injection → Implicit Parameters | Reader Monad 

### ISSUE THREAD

**Issue by asiloh** [thma/LtuPatternFactory#24]
[Implicit parameters in Haskell](https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/implicit_parameters.html)
[Dependency injection using the Reader monad (F#)](https://fsharpforfunandprofit.com/posts/dependencies-3/)

**Comment by thma** [comment]
Hi, thanks for your contribution!

I think the reader monad example can be a usefull addition!

Regarding the implicit parameters I've still some questions.
Looking at the given example:

```haskell
sortBy :: (a -> a -> Bool) -> [a] -> [a]

sort   :: (?cmp :: a -> a -> Bool) => [a] -> [a]
sort    = sortBy ?cmp
```

It look's quite like an ordinary partial application, but with a dynamically type cmp function.

As I have already covered partial application as the most straight forward implementation of CI in functional languages, I'm not sure what additional benefit is gained by the usage of implicit parameters?

**Comment by asiloh** [comment]
Hi, this guide is really handy!
As for the benefits of implicit parameters, since I haven't used them in practice, I can't clearly explain what benefits they offer. 
There are some thread and post where people debate the use of implicit parameters:

[Who Still Uses ReaderT](https://hugopeters.me/posts/10/) 

[Reddit: Who Still Uses ReaderT ](https://old.reddit.com/r/haskell/comments/m8o88a/who_still_uses_readert/) 
[At this comment](https://old.reddit.com/r/haskell/comments/m8o88a/who_still_uses_readert/grkh17q/), Edward Kmett argues that it can bring benefits when used properly.

[What's wrong with ImplicitParams](https://chrisdone.com/posts/whats-wrong-with-implicitparams/)

**Comment by thma** [comment]
Hi again,

I've just added a short section on Reader Monad and implicit parameters which links to "Who still uses ReaderT" and "What's wrong with implicitParams"

Thanks again for your contribution, That's really appreciated!
