### ISSUE TITLE
Currying vs. partial application

### ISSUE THREAD

**Issue by drever** [thma/LtuPatternFactory#7]
Hi thma,

great project! It's important to connect the OO world and the FP world. Doing so by matching design patterns to type classes should give valuable insights.

In the Section "Functor -> Strategy" there is a comment about currying

     context :: Num a => (a -> a) -> [a] -> [a]
     context f l = map f l
      -- according to the rules of currying this can be abbreviated to:
     context = map
 
Currying is taking a function from `(a, b) -> c` to `a -> b -> c`, so I'm not sure that just leaving the function arguments is really [currying](https://wiki.haskell.org/Currying). It is rather related to the [pointfree](https://wiki.haskell.org/Pointfree) style. 

So maybe the comment should rather say "using point free style", or "in Haskell it is possible to not write the arguments".

Best,
Johannes

**Comment by thma** [comment]
Thanks for raising this issue, i‘ll correct that comment

**Comment by thma** [comment]
Fixed the comment according to your suggestion. 
Thanks a ton !
